<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>io.github.guillex7</groupId>
    <artifactId>explodeany-parent</artifactId>
    <version>1.13.0</version>
    <name>ExplodeAny parent project</name>

    <packaging>pom</packaging>

    <developers>
        <developer>
            <name>GuilleX7</name>
            <email>GuillermoX7@gmail.com</email>
            <roles>
                <role>Author</role>
            </roles>
        </developer>
    </developers>

    <modules>
        <module>compatibility/common</module>
        <module>compatibility/manager</module>
        <module>compatibility/bukkit/v1-8</module>
        <module>compatibility/bukkit/v1-8-3</module>
        <module>compatibility/bukkit/v1-9</module>
        <module>compatibility/bukkit/v1-13</module>
        <module>compatibility/bukkit/v1-13-paper</module>
        <module>compatibility/bukkit/v1-14</module>
        <module>compatibility/bukkit/v1-14-paper</module>
        <module>compatibility/bukkit/v1-16-1</module>
        <module>compatibility/bukkit/v1-16-1-paper</module>
        <module>compatibility/bukkit/v1-19-4-paper</module>
        <module>compatibility/bukkit/v1-20</module>
        <module>compatibility/bukkit/v1-21-paper</module>
        <module>compatibility/coreprotect/api-v7</module>
        <module>compatibility/worldguard/api-v6</module>
        <module>compatibility/worldguard/api-v7</module>
        <module>compatibility/factions/api-v3</module>
        <module>explodeany</module>
    </modules>

    <properties>
        <explodeany.version>1.13.0</explodeany.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>8</maven.compiler.release>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
            </plugin>

            <!-- Install dev.pixelmania.throwablecreepereggs -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.1.2</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <id>install-dev-pixelmania-throwablecreepereggs</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>clean</phase>
                        <configuration>
                            <groupId>dev.pixelmania</groupId>
                            <artifactId>throwablecreepereggs</artifactId>
                            <version>2.3.0</version>
                            <packaging>jar</packaging>
                            <file>${basedir}/lib/dev.pixelmania.throwablecreepereggs-2.3.0.jar</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>

                    <execution>
                        <id>install-com-massivecraft-factions-Factions</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>clean</phase>
                        <configuration>
                            <groupId>com.massivecraft.factions</groupId>
                            <artifactId>Factions</artifactId>
                            <version>3.4.0-alpha-1</version>
                            <packaging>jar</packaging>
                            <file>
                                ${basedir}/lib/com.massivecraft.factions.Factions-3.4.0-alpha-1.jar</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>

                    <execution>
                        <id>install-com-massivecraft-massivecore-MassiveCore</id>
                        <goals>
                            <goal>install-file</goal>
                        </goals>
                        <phase>clean</phase>
                        <configuration>
                            <groupId>com.massivecraft.massivecore</groupId>
                            <artifactId>MassiveCore</artifactId>
                            <version>3.4.0-alpha-1</version>
                            <packaging>jar</packaging>
                            <file>
                                ${basedir}/lib/com.massivecraft.massivecore.MassiveCore-3.4.0-alpha-1.jar</file>
                            <generatePom>true</generatePom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <repositories>
        <!-- org.spigotmc.spigot-api -->
        <repository>
            <id>spigot-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <!-- com.destroystokyo.paper.paper-api, dev.folia.folia-api -->
        <repository>
            <id>papermc</id>
            <url>https://repo.papermc.io/repository/maven-public/</url>
        </repository>
        <!-- me.zombie_striker.QualityHarmory -->
        <repository>
            <id>codemc-repo</id>
            <url>https://repo.codemc.org/repository/maven-public/</url>
        </repository>
        <!-- net.coreprotect.coreprotect -->
        <repository>
            <id>playpro</id>
            <url>https://maven.playpro.com</url>
        </repository>
        <!-- com.sk89q.worldguard.worldguard-bukkit -->
        <repository>
            <id>enginehub</id>
            <url>https://maven.enginehub.org/repo/</url>
        </repository>
        <!-- me.clip.placeholderapi -->
        <repository>
            <id>placeholderapi</id>
            <url>https://repo.helpch.at/releases/</url>
        </repository>
        <!-- com.github.DerPavlov.Cannons -->
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
</project>