# Hey! This file will regenerate each time you load ExplodeAny, so don't be scared if you remove it!
# It will help you to understand how to configurate the plugin. It contains an explanation of every
# section and configuration item there. Happy configuration time!

UseBlockDatabase: false                             # Choose whether to use a database or not. It's not necessary at all.
                                                    # The database will store block information so damaged blocks will remain
                                                    # damaged after a server restart. However, database file can grow a lot, so
                                                    # it's up to you.

CheckBlockDatabaseAtStartup: false                  # Only used if UseBlockDatabase is enabled.
                                                    # This will remove blocks that have already disappeared in the world or have been replaced
                                                    # from the database.
                                                    # This can help reducing database size, but may also load the chunks where the blocks were
                                                    # located at.
                                                 
BlockDurability: 100.0                              # Maximum and initial durability of every block handled by ExplodeAny.
                                                    # Minimum is 1.0. Default is 100.0.

Groups:                                             # Named groups of materials, entitys or whatever. You can even put a mix of materials
                                                    # and exploding entities. Whenever you use the group in a certain section, the
                                                    # plugin will choose only the values that make sense for that section. If no value
                                                    # in the group makes sense for the section, then it will be treated as an invalid group.
                                                    # You can use whatever name you like for the groups, but if group's name coincides
                                                    # with a valid material, entity or whatever's name of that section, then the single
                                                    # entity (NOT the group) will be selected.
                                                    
                                                    # Using groups mean that items can conflict. When a item appears more than once in the
                                                    # same section, the following will happen depending on the section where the conflict
                                                    # appeared:
                                                    #
                                                    # EXPLODING ENTITIES:
                                                    # 1. If a entity appears in two or more groups, then the material configurations
                                                    #    will try to merge without overwriting each other. If a material configuration
                                                    #    for an entity appears in both groups, then the material configuration of the
                                                    #    group that appears first in the configuration is applied.
                                                    # 2. If a entity appears in one or more groups but also as an individual item,
                                                    #    then rule 1 applies, and after that, the individual configuration will be merged,
                                                    #    overwriting if necessary (has greater priority than groups).
                                                    #
                                                    # MATERIAL CONFIGURATIONS:
                                                    # 1. If a material configuration appears in two or more groups, then only the material
                                                    #    configuration of the group that appears first in the configuration will be applied.
                                                    # 2. If a material configuration appears in two or more groups but also as an individual
                                                    #    item, then the individual configuration will be applied.
    unbreakableBlocks:
        - OBSIDIAN
        - CRYING_OBSIDIAN
        - BEDROCK
    dangerousEntities:
        - PRIMED_TNT
        - CREEPER

VanillaEntity:
    PRIMED_TNT:                                     # Vanilla entities that explode, allowed entities are:
                                                    # WITHER, ENDER_CRYSTAL, PRIMED_TNT, CREEPER, CHARGED_CREEPER,
                                                    # FIREBALL, DRAGON_FIREBALL, SMALL_FIREBALL, WITHER_SKULL, CHARGED_WITHER_SKULL
                                                    # Groups can also be used here.
                                                
        Properties:                                 # This section allows to configure some properties of the exploding entity itself.
                                                    # It is not mandatory.
                                                    
            ExplosionDamageBlocksUnderliquid: true  # Overrides the explosion caused by this entity when it takes place under any liquid.
                                                    # It will be replaced with a explosion that can damage blocks, even underwater.
                                                    # This allows to break, for example, any block that would normally break in the
                                                    # overworld. Blocks managed by ExplodeAny will keep their behaviour!
                                                    
            UnderliquidExplosionFactor: 0.5         # The explosion power of the overriding explosion will be the same as the original,
                                                    # but you may want to change it as it takes place under a liquid.
                                                    # Explosion power will be multiplied by this factor when UnderliquidExplosionFactor
                                                    # is enabled and the explosion takes place underwater.
                                                    # Minimum is 0.0, which means it will disabled
                                                    # Default is 1.0, which means that water doesn't affect explosion power
                                                
        Materials:                                  # This section contains the materials that will be managed by the plugin.
                                                    # It is not mandatory: if this section doesn't exist, the plugin will understand that
                                                    # every section in the entity is a material. That can be used as a shortcut when
                                                    # you don't want to add entity properties, but to list directly the affected materials.
                                                    # The damage to all those materials is "simulated" by the plugin and managed
                                                    # by these settings. ExplodeAny will override even the damage taken by materials
                                                    # that would break in a regular Vanilla explosion, meaning that you could make them
                                                    # indestructibles.
                                                    
            OBSIDIAN:                               # Valid values are all materials listed in
                                                    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html.
                                                    # WATER and LAVA are not allowed. Blocks managed by this plugin will be damaged as
                                                    # set below even underwater, and for those which are unmanaged in this section, see
                                                    # ExplosionDamageBlocksUnderliquid above.
                                                    # Groups can also be used here.
                                                    
                Damage: 50.0                        # Regular damage taken when impacted by the explosion.
                                                    # Minimum is 0.0, which means the block isn't affected by the explosion (disabled).
                                                    # A value greater than BlockDurability is allowed.
                                                    # Default is BlockDurability.
                                                    
                DropChance: 0.0                     # Chance of dropping this block as an item when it breaks.
                                                    # Maximum is 100.0 (always drop), minimum [default] is 0.0 (never drops).
                                                    
                DistanceAttenuationFactor: 0.0      # Indicates how much should be taken into account the distance
                                                    # from the center of the explosion in the damage estimation.
                                                    # Minimum [default] is 0.0, which means that all blocks in range will
                                                    # take the same amount of damage.
                                                    # Maximum is 1.0, which means that damage decreases linearly with respect to
                                                    # distance. (not recommended)
                
                ExplosionRadiusFactor: 0.5          # Allows to change the radius of the explosion for this block, so that
                                                    # every block whose distance from the center is greater than the explosion radius
                                                    # multiplied by this factor is not affected by the explosion.
                                                    # Minimum is 0.0, which makes the effective radius equal 0 (no damage)
                                                    # A value of 1.0 would mean the effective radius equals the explosion
                                                    # radius.
                                                    # Default is 0.5.
                                                    
                                                    # Effective damage is calculated with the following formula:
                                                    # finalDamage =  damage * (1 - c(d - 1) / dmax)  if 1 <= d < dmax
                                                    #                0                               if dmax <= d
                                                    # c = distance attenuation factor
                                                    # d = distance from the center (always greater or equal 1)
                                                    # dmax = radius of the explosion (after applying explosionRadiusFactor).
                
                UnderwaterDamageFactor: 1.0         # Damage will be multiplied by this factor when explosion takes place underliquid.
                                                    # Minimum is 0.0, which means it will disable underliquid damage.
                                                    # Default is 1.0, which means that water doesn't affect damage.
                                                    # A value greater than 1.0 means damage underliquid is magnified.
                
                FancyUnderwaterDetection: false     # Sets the underliquid detection procedure to use.
                                                    # False means that the UnderwaterDamageFactor will be applied if and only if the
                                                    # centre of the explosion is a block of liquid, so every block will be affected or
                                                    # not depending only on the explosion. (faster)
                                                    # True means that, for each block, a scan of its trajectory will be performed in
                                                    # search of liquid. This allows to apply UnderwaterDamageFactor on every block independently,
                                                    # and also improves the detection in general. (slower)
            
CannonProjectile:                                   # This section can be configured for use with Cannons plugin. This plugin
                                                    # doesn't require Cannons at all, but it will detect whether it's loaded
                                                    # or not and enable support automatically.
                                                    
    diamond:                                        # Cannon projectile IDs
        Properties:
            ExplosionDamageBlocksUnderliquid: true  # Overriding the original projectile explosion also means that all side effects 
                                                    # managed by Cannons (like spawning fireworks, cluster bombs, etc.) will be disabled.
                                                    # We are working to improve this.
            UnderliquidExplosionFactor: 0.5
        Materials:                                  # Contrary to what happens in the VanillaEntity section, and in an unfortunate way,
                                                    # we can't override the behaviour of blocks that would break in regular conditions
                                                    # when a Cannon projectile explodes. That means that putting breakable materials here
                                                    # won't have the desired effect. We are working to improve this.
            OBSIDIAN:
                Damage: 50.0
                DropChance: 0.0
                DistanceAttenuationFactor: 0.0
                ExplosionRadiusFactor: 0.5
                UnderwaterDamageFactor: 1.0
                FancyUnderwaterDetection: false
            
Locale:                                             # All colors and modifiers are available for locale messages.
                                                    # For ChecktoolUse and ChecktoolNotHandled, you can use some variables:
                                                    #   %MATERIAL% represents the clicked block's type,
                                                    #   %B_X% the X coordinate of the targeted block
                                                    #   %B_Y% the Y coordinate of the targeted block
                                                    #   %B_Z% the Z coordinate of the targeted block
                                                    # These are only available for ChecktoolUse message:
                                                    #   %DURABILITY% the clicked block's durability and
                                                    #   %MAX_DURABILITY% the maximum durability a block can have (same as BlockDurability)
                                                
    NotAllowed: "You are not allowed to perform this action!"
    OnlyPlayerAllowed: "Only players can perform this action!"
    EnterChecktoolMode: "You can now right-click a block with your bare hand to display block durability"
    LeaveChecktoolMode: "You can no longer check for a block durability"
    ChecktoolUse: "%B_X% / %B_Y% / %B_Z% // %MATERIAL% (%DURABILITY% / %MAX_DURABILITY%)"
    ChecktoolNotHandled: "%MATERIAL% is not handled by the current configuration"
    Reloaded: "Reloaded successfully!"