name: ExplodeAny
main: io.github.guillex7.explodeany.ExplodeAny
version: 1.3.0
api-version: 1.16
description: Allows to break any unbreakable block with explosions!
author: GuilleX7
website: https://github.com/GuilleX7/ExplodeAny
softdepend: [Cannons]
commands:
    explodeany:
        description: "General command"
        aliases: [eany]
permissions:
    explodeany.*:
        description: "Gives all permissions to a player"
        default: op
        children:
            explodeany.checktool: true
            explodeany.reload: true
            explodeany.about: true
    explodeany.checktool:
        description: "Gives permission to use checktool command"
        default: op
    explodeany.reload:
        description: "Gives permission to use reload command"
        default: op
    explodeany.about:
        description: "Gives permission to use about command"
        default: true