UseBlockDatabase: false
CheckBlockDatabaseAtStartup: false
BlockDurability: 100.0
EnableMetrics: true

Checktool:
    AlwaysEnabled: false
    EnabledByDefault: false
    PreventActionWhenCheckingHandledBlocks: true
    PreventActionWhenCheckingNonHandledBlocks: true
    SilentWhenCheckingOnDisabledWorlds: false
    SilentWhenCheckingWithoutPermissions: false
    SilentWhenCheckingNonHandledBlocks: false
    SilentWhenCheckingHandledBlocks: false
    ShowBossBar: false
    BossBarColor: PURPLE
    BossBarStyle: SOLID
    BossBarDuration: 1500ms

Groups: {}

Materials: {}

VanillaEntity: {}

CannonProjectile: {}

MagicEntity: {}

QualityArmory: {}

ThrowableCreeperEggs: {}

CustomEntity: {}

Locale:
    NotAllowed: "You are not allowed to perform this action!"
    Usage: "Usage: %DESCRIPTION%"
    OnlyPlayerAllowed: "Only players can perform this action!"
    PlayerDoesntExist: "Player %NAME% doesn't exist in the server!"
    PlayerIsOffline: "Player %NAME% must be online to perform that"
    EnterChecktoolMode: "You can now right-click a block with %PRETTY_ITEM% to display block durability"
    LeaveChecktoolMode: "You can no longer check for a block durability"
    ChecktoolToggledOn: Checktool mode toggled on for player %NAME%
    ChecktoolToggledOff: Checktool mode toggled off for player %NAME%
    ChecktoolUse: "Block health: %DURABILITY_PERCENTAGE%% (%PRETTY_MATERIAL%)"
    ChecktoolUseBossBar: "%PRETTY_MATERIAL%: %DURABILITY_PERCENTAGE%%"
    ChecktoolSet: "Checktool successfully set to %PRETTY_ITEM%!"
    ChecktoolNotPersisted: "Checktool item was set to %PRETTY_ITEM%, but it couldn't be persisted"
    ChecktoolGiven: "A checktool (%PRETTY_ITEM%) was given to player %NAME%"
    ChecktoolReset: "Checktool successfully reset to bare hand (Air)"
    ChecktoolNotHandled: "%PRETTY_MATERIAL% is not handled by the current configuration"
    ChecktoolInfo: "Current checktool item: %PRETTY_ITEM%"
    ChecktoolAlwaysEnabled: "Checktool can't be toggled off because it's always enabled"
    DisabledInThisWorld: "This functionality is disabled in this world"
    Reloaded: "Reloaded successfully!"
    DebugEnabled: "Debug mode has been enabled"
    DebugDisabled: "Debug mode has been disabled"

LocalePrefix: "[ExplodeAny] "

DisabledWorlds: []

WorldHoleProtection: {}
