name: ExplodeAny
main: io.github.guillex7.explodeany.ExplodeAny
version: 1.5.0
api-version: 1.13
description: Allows to break any unbreakable block with explosions!
author: GuilleX7
website: https://github.com/GuilleX7/ExplodeAny
softdepend: [Cannons, Magic]
commands:
    explodeany:
        description: "General command"
        aliases: [eany]
permissions:
    explodeany.*:
        description: "Gives all permissions"
        default: op
        children:
            explodeany.checktool.*: true
            explodeany.reload: true
            explodeany.about: true
    explodeany.checktool.*:
        description: "Gives all permissions about checktool"
        default: op
        children:
            explodeany.checktool.use: true
            explodeany.checktool.toggle: true
            explodeany.checktool.give: true
            explodeany.checktool.set: true
            explodeany.checktool.reset: true
    explodeany.checktool.use:
        description: "Gives permission to use checktool"
        default: op
    explodeany.checktool.toggle:
        description: "Gives permission to toggle checktool use"
        default: op
    explodeany.checktool.give:
        description: "Gives permission to give checktool items"
        default: op
    explodeany.checktool.set:
        description: "Gives permission to set checktool item"
        default: op
    explodeany.checktool.reset:
        description: "Gives permission to reset checktool item"
        default: op
    explodeany.reload:
        description: "Gives permission to use reload command"
        default: op
    explodeany.about:
        description: "Gives permission to use about command"
        default: true