name: ExplodeAny
main: io.github.guillex7.explodeany.ExplodeAny
version: 1.12.0-folia.1
api-version: 1.13
description: Allows to break any unbreakable block with explosions!
author: GuilleX7
website: https://github.com/GuilleX7/ExplodeAny
softdepend: [Cannons, Magic, QualityArmory, ThrowableCreeperEggs]
folia-supported: true
commands:
    explodeany:
        description: "General command"
        aliases: [eany]
permissions:
    explodeany.*:
        description: "Gives all permissions"
        default: op
        children:
            explodeany.checktool.*: true
            explodeany.configuration.*: true
            explodeany.debug.*: true
            explodeany.reload: true
    explodeany.checktool.*:
        description: "Gives all permissions about checktool"
        default: op
        children:
            explodeany.checktool.use: true
            explodeany.checktool.enable: true
            explodeany.checktool.enable.others: true
            explodeany.checktool.disable: true
            explodeany.checktool.disable.others: true
            explodeany.checktool.toggle: true
            explodeany.checktool.toggle.others: true
            explodeany.checktool.give: true
            explodeany.checktool.set: true
            explodeany.checktool.info: true
            explodeany.checktool.reset: true
    explodeany.checktool.use:
        description: "Gives permission to use checktool"
        default: op
    explodeany.checktool.enable:
        description: "Gives permission to enable checktool use for yourself"
        default: op
    explodeany.checktool.enable.others:
        description: "Gives permission to enable checktool use for others"
        default: op
    explodeany.checktool.disable:
        description: "Gives permission to disable checktool use for yourself"
        default: op
    explodeany.checktool.disable.others:
        description: "Gives permission to disable checktool use for others"
        default: op
    explodeany.checktool.toggle:
        description: "Gives permission to toggle checktool use for yourself"
        default: op
    explodeany.checktool.toggle.others:
        description: "Gives permission to toggle checktool use for others"
        default: op
    explodeany.checktool.give:
        description: "Gives permission to give checktool items"
        default: op
    explodeany.checktool.set:
        description: "Gives permission to set checktool item"
        default: op
    explodeany.checktool.info:
        description: "Gives permission to show checktool item info"
        default: op
    explodeany.checktool.reset:
        description: "Gives permission to reset checktool item"
        default: op
    explodeany.configuration.*:
        description: "Gives all permissions about configuration"
        default: op
        children:
            explodeany.configuration.show: true
    explodeany.configuration.show:
        description: "Gives permission to show configuration"
        default: op
    explodeany.debug.*:
        description: "Gives all permissions about debugging"
        default: op
        children:
            explodeany.debug.enable: true
            explodeany.debug.disable: true
    explodeany.debug.enable:
        description: "Gives permission to enable debug mode"
        default: op
    explodeany.debug.disable:
        description: "Gives permission to disable debug mode"
        default: op
    explodeany.reload:
        description: "Gives permission to use reload command"
        default: op
